### ISSUE TITLE
Base image dependencies should be output before building the image.

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#11]

**Comment by ehotinger** [comment]
@sajayantony  I think you meant to close #61 with #62 but closed this one instead.

**Comment by sajayantony** [comment]
Correct. Thanks for reopening this one.

**Comment by ehotinger** [comment]
@sajayantony @northtyphoon thoughts on this - do we still want it, yay/nay? Marking as low priority.

**Comment by sajayantony** [comment]
Yes this is low priority at this point.

- Sajay

On Apr 21, 2018, at 12:47 AM, Eric Hotinger <notifications@github.com<mailto:notifications@github.com>> wrote:


@sajayantony<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsajayantony&data=02%7C01%7Csajaya%40microsoft.com%7Cbdf6057180304ca1da2608d5a75c1705%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636598936320471369&sdata=595xT6KrIa889asF447k9tYyiJXYZEcRVTXvgC07%2FQQ%3D&reserved=0> @northtyphoon<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnorthtyphoon&data=02%7C01%7Csajaya%40microsoft.com%7Cbdf6057180304ca1da2608d5a75c1705%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636598936320471369&sdata=tKw2oknLfowWjSJfjm4e3HgShPa3d8IJDfTrCqkIGFg%3D&reserved=0> thoughts on this - do we still want it, yay/nay? Marking as low priority.
