### ISSUE TITLE
[CLI] Support Windows isolation with an empty string

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#131]
`--isolation=""` should be equivalent to `--isolation="default"` - right now the value `""` is treated as valid but `--isolation` isn't appended to `build` unless it's `!= ""`. 

See
https://github.com/Azure/acr-builder/blob/2e2b8dd2c98b955f4028e7c893284b1cf68af3f8/pkg/commands/docker.go#L141-L143

**Comment by northtyphoon** [comment]
I see the following commands are the same. The above code seems fine.

```
docker build .
docker build --isolation .
docker build --isolation=default .
```

BTW: The README needs to be updated. It still mentiones `--hyperv-isolation`. @mnltejaswini

**Comment by ehotinger** [comment]
I see, yeah it'll choose from the Daemon's settings in that case. Just made this as a reminder to myself initially. Closing; don't worry about the README, I'll refactor it all anyways. 👍
