### ISSUE TITLE
Support for exit codes

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#136]
- Add support for `exitedWith` and `exitedWithout` - to run steps based on other steps' exit codes.

- Update docs

Core concept here is to refactor the DAG processing so that it's not removing edges; instead it should iterate through edges and check parents for status

**Comment by sajayantony** [comment]
Adding this for discussion 
```
steps:
    - cmd: docker manifest inspect {{.Run.Registry}}/non-existant:image
      exitedWith: [1]
    - cmd: bash ls
```
