### ISSUE TITLE
WARNING regarding config file  when doing Windows container builds

### ISSUE THREAD

**Issue by mnltejaswini** [Azure/acr-builder#176]
Windows container build shows the following warnings

- [x] Fix - WARNING: Error loading config file: C:\Users\ContainerAdministrator\.docker\config.json: invalid character 'ÿ' looking for beginning of value
WARNING! Your password will be stored unencrypted in C:\Users\ContainerAdministrator\.docker\config.json.

- [ ] Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

**Comment by sajayantony** [comment]
@Jinhuafei - Does your fix address this?

**Comment by Jinhuafei** [comment]
Yes.

**Comment by sajayantony** [comment]
So can we close this? @mnltejaswini

**Comment by ehotinger** [comment]
No, not yet.

**Comment by ehotinger** [comment]
To clarify: the real fix is to move to the Windows credential manager and ensure that we can pass credentials throughout steps from the host.

**Comment by sajayantony** [comment]
Ok updated the bug with tasks.

**Comment by sajayantony** [comment]
But what about - #176

**Comment by sajayantony** [comment]
@Jinhuafei  - Do you want to fix this item for Ignite?

**Comment by Jinhuafei** [comment]
Will give it a try.

**Comment by ehotinger** [comment]
@northtyphoon  + @Jinhuafei closing this for now as per our previous discussion. Shouldn't be necessary at this point.
