### ISSUE TITLE
Image prefixes for tasks

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#223]
If specified, the `imagePrefix` will be added to all `cmd`, `{imagePrefix}/{imageName}`.

**Comment by sajayantony** [comment]
Do we just want to avoid this. I remember VSTS tasks did something similar and it confused users. 
If we do add this we should emit this value upfront so that its obvious in some form.

**Comment by ehotinger** [comment]
@sajayantony this is something @SteveLasker mentioned in passing. It can definitely cause confusing behavior IMO. If a lot of people want it, we can consider adding it. Issue can be left open for tracking, but no rush to implement it.

**Comment by sajayantony** [comment]
De-prioritizing syntactic sugar for now.

**Comment by ehotinger** [comment]
Closing since we decided not to support this a while ago.
