### ISSUE TITLE
build/task run output should highlight the steps

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#225]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
**What happened?**:
When running multiple steps with acr task run, it's difficult to associate the output with a specific step

**What did you expect to happen?**:
Similar to multi-stage dockerfile builds, each step is identified.
If no id is specified, use the numeric index of the step. if an id is specified, provide that id name
Would also like to see the heading in color, to easily differentiate/identify a step heading from other goo in the output stream

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment**:

**Comment by ehotinger** [comment]
This is the same as https://github.com/Azure/acr-builder/issues/137
