### ISSUE TITLE
Base Image Updates Trigger Twice when 2 tags are dependent

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#238]
**BUG REPORT**:

**What happened?**:
Using https://github.com/demo42/helloworld as a reference, the helloworld image is based on https://github.com/demo42/baseimage-node

When a build-task has one tag, updating the base image triggers a single build of a dependent build-task
However, when a build-task has two or more tags defined, a build is triggered for each tag. 
```sh
az acr build-task create \
  -t demo42/helloworld:{{.Build.ID}} \
  -t demo42/helloworld:release \
  -n demo42helloworld \
  --context https://github.com/demo42/helloworld \
  --git-access-token $PAT
```
**What did you expect to happen?**:
A single dependency for base images referenced in the build defintion

**How do you reproduce it (as minimally and precisely as possible)?**:
Follow steps in https://github.com/demo42/helloworld/blob/master/README.md
**Anything else we need to know?**:

**Environment**:

**Comment by djyou** [comment]
This is fixed and will be deployed in the next release.

**Comment by SteveLasker** [comment]
Awesome. What’s the timing for the next release?

On Aug 20, 2018, at 7:35 PM, Dongjiang You <notifications@github.com<mailto:notifications@github.com>> wrote:


This is fixed and will be deployed in the next release.
