### ISSUE TITLE
Not accounting for comments

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#241]
**BUG REPORT**:

**What happened?**:
**task.yaml**
```sh
version: 1.0.0
steps:
  - run: bash ls
  - run: build -t helloworld:release .
  - run: git clone https://github.com/demo42/deploy.git
  - run: bash ls 
    workDir: ./deploy
  #- run: {{.Run.Registry}}/functions/helm:latest 
```
` az acr build -f tasks.yaml .`
errored:
```sh
Error: Error while rendering templates: Failed to execute template: tasks.yaml. Err: template: tasks.yaml:8:16: executing "tasks.yaml" at <.Run.Registry>: can't evaluate field Registry in type interface {}
```

**What did you expect to happen?**:

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment**:

**Comment by ehotinger** [comment]
@SteveLasker try again with `.Build`. Prod deployed bits haven't been renamed. It also doesn't support version right now and version is supposed to be a string: `v1.0.0`.

**Comment by ehotinger** [comment]
More info: the templating as-of-now is written in such a way that it works on arbitrary text, so `#` is meaningless to interpret for it, since it's only a comment in YAML. Assuming that you pass in a valid expression, it will render the text with the comment; the YAML parser and DAG traversal will then ignore that node.

**Comment by sajayantony** [comment]
Should we just skip comments all-together?

**Comment by ehotinger** [comment]
We will dynamically rewrite the provided template in #263. Any line beginning with `#` after trimming whitespace will be removed from the template.
