### ISSUE TITLE
acb build doesn't prefix image tag

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#242]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened?**:

`acb build --registry myregistry.azurecr.io --push -t image:v1 ...`

It failed as the image was tagged as `image:v1` but pushed to `myregistry.azurecr.io/image:v1`

**What did you expect to happen?**:

The output image is tagged as `myregistry.azurecr.io/image:v1` and pushed to the registry successfully.

**Anything else we need to know?**:

It looks the prefix only applies on the push not on the `rendered` build step.

https://github.com/Azure/acr-builder/blob/04dfc488769578ae2ef403d0e9e2c3e65c20ea70/cmd/build.go#L120-L141

**Comment by ehotinger** [comment]
@northtyphoon not sure about this one. How would you know whether or not a tag should be prefixed without rendering? I'm guessing you think it's confusing to output the rendering when it's not "exact"?
