### ISSUE TITLE
Allow Home volume name to be accessible through Run

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#252]
- Allow the home volume's name to be accesible through `.Run.`

**Comment by ehotinger** [comment]
#263 introduces `.Run.SharedContextDir`

/cc @sajayantony

**Comment by sajayantony** [comment]
Thinking out loud here. We use Dir and Directory which is a bit inconsistent.

**Comment by ehotinger** [comment]
@sajayantony updated to `SharedContextDirectory` in the aforementioned PR.
