### ISSUE TITLE
Assume push to ACR_BUILD_DOCKER_REGISTRY even if it is not defined in docker-compose image name

### ISSUE THREAD

**Issue by shhsu** [Azure/acr-builder#26]
Talk to @northtyphoon and @mnltejaswini 

Currently we require user to explicitly refer to ```ACR_BUILD_DOCKER_REGISTRY``` in docker compose file as image name. i.e.

```
image: ${ACR_BUILD_DOCKER_REGISTRY}hello-builder-1.0-${ACR_BUILD_BUILD_NUMBER}
```

This means when user first come onboard they would have to modify their docker-compose file. It is not desirable.

We should assume the push goes to ```ACR_BUILD_DOCKER_REGISTRY``` if no registry name is specified in the image name.

**Comment by northtyphoon** [comment]
docker-compose support has been removed
