### ISSUE TITLE
Task with context path in the git url is not processed

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#261]
```
...-f hello-world.yaml https://github.com/AzureCR/acr-task.git#:examples
Sending build context to ACR.
...
Error: failed to load template at path hello-world.yaml: stat /workspace/hello-world.yaml: no such file or directory
 
```

**Comment by ehotinger** [comment]
@sajayantony it would be helpful to also describe your expectations for this one, i.e. would we set the workingDirectory on all subsequent commands to start at `examples`? What if someone specifies `workingDirectory` on the `Task` level and the `Step` level? Do we concatenate all the way down, etc.

**Comment by SteveLasker** [comment]
What does Docker do?

**Comment by sajayantony** [comment]
I think the point of expressing it this way is that the builder need not care about anything outside the examples folder. 

This also means that `docker build .` if executed should be under that path and similarly 
acb would also use that path as the context. 

Content above that should be invisible and hence not-mounted into the /workspace. 
Basically what I am seeing here is that `context = ./examples` and all commands under that expect that as the root relative paths for build and acb. 
Do you see a concern with that behavior and in anyway different from docker's interpretation. 

```YAML
steps: 
- build: -f . # this file would be besides examples if we ran it this way
```

```sh
examples
  | - Dockerfile
  | - app.js
``` 
    
```dockerfile
FROM nodejs:alpine
COPY . /app
...
```

**Comment by ehotinger** [comment]
Yes, because it's not a first-class feature of a git remote to be able to do that. It's effectively a cd and it's always a full clone. So we would have to clone, copy a subfolder, delete the rest, etc.

**Comment by ehotinger** [comment]
@sajayantony what are your expectations for how the `workingDirectory` properties of the `Task` and `Step` behave after this change? The initial working directory of the builder will be set to the context specified in the fragment now, but it will require users to set `workingDirectory` in their `Task` to have it propagate to all steps. We could introduce a parameter that sets that property for them in the `Task` automatically to make it more magical.

**Comment by SteveLasker** [comment]
Let’s please whiteboard and discuss before committing changes. We likely need to change, but we can work around the current model to land a preview. I’d just like to focus on stability, even if it has quirks until we know what we want to change.
