### ISSUE TITLE
az acr build should echo the registry name

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#271]
**BUG REPORT**:

**What happened?**:
When using `az acr build ...` we've com accustomed to setting the default registry with `az configure --defaults acr=foo`. However, several context switches can happen for a developer, using different shells. **What did you expect to happen?**:
To help minimize confusion, we should add the registry name to the initial output.
Proposal is to simply expand
```sh
Sending build context (946.000 Bytes) to ACR...
```
to
`Sending build context (946.000 Bytes) to` [azure-registry]

```sh
az acr build -f hello-world-task.yaml .
Packing source code into tar file to upload...
Excluding '.git' based on default ignore rules
Sending build context (946.000 Bytes) to demo42.azurecr.io
'--image -t' is not provided. Skipping image push after build.
Queued a build with build ID: ba2n
```

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment**:

**Comment by sajayantony** [comment]
This should be moved to CLI and not in the builder.

**Comment by ehotinger** [comment]
Moved to https://github.com/AzureCR/azure-cli/issues/227
