### ISSUE TITLE
ACR build should simplify the digits for seconds

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#272]
**BUG REPORT**:

**What happened?**:
acr build/task steps reports 6 digits and final execution reports 9 digits of accuracy for elapsed time. 

**What did you expect to happen?**:
At most, a single decimal of accuracy for execution time. "KIIS"

**How do you reproduce it (as minimally and precisely as possible)?**:
```sh
az acr build ...
...
2018/09/04 16:05:07 Step ID acb_step_0 marked as successful (elapsed time in seconds: 7.617887)
Build ID: ba2n was successful after 18.637986064s
```
Each step and final build should limit to a single decimal place, rounding up. 

**Anything else we need to know?**:

**Environment**:

**Comment by ehotinger** [comment]
Closing this since it doesn't belong on this repo, but the PR to round duration to the nearest second is out.
