### ISSUE TITLE
ACR Task cmd should make port 80 available

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#281]
**BUG REPORT**:
Expectation that I should be able to access a running container w/port 80, if delcared
```yaml
ports: ["80:80"]
```

**What happened?**:
Got an error the port was occupied
**What did you expect to happen?**:
Be able to use normal ports I would use in other environments. 

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

There are likely other ranges, but I'd expect to be able to use:
- 80, 443
- 8000 range
- 5000 range
- 1433 - for SQL scenarios

Can we put our runner on some distant, random port that nobody would expect to use?
**Environment**:

**Comment by ehotinger** [comment]
Closing - this PR was made upstream. Alongside https://github.com/Azure/acr-builder/pull/295 there should be little reason (currently) to map to the host network.
