### ISSUE TITLE
--build-args should validate it has meaningful content

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#283]
**BUG REPORT **:
When passing --build-args, input parameters should be validated it has something to act upon before queing up a run

**What happened?**:
```sh
az acr build -t demo42/quotes-api:{{.Build.ID}} -f ./src/QuoteService/Dockerfile --build-arg demo42.azurecr.io .
```

I had forgotten to put the name of the build arg
```sh
az acr build -t demo42/quotes-api:{{.Build.ID}} -f ./src/QuoteService/Dockerfile --build-arg REGISTRY_NAME=demo42.azurecr.io .
```
**What did you expect to happen?**:
Some error string that says invalid format for build-arg

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment**:

**Comment by ehotinger** [comment]
This is by design right now, the builder will say that the argument "demo42.azurecr.io" is unused in the output.
