### ISSUE TITLE
az acr build should show a warning when {{.Build.ID}} is used, pointing to {{.Run.ID}}

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#287]
**BUG REPORT**:
As we GA ACR Build, we're deprecating .Build.ID in lieu of .Run.ID
Please add text that says:
`.Build.ID is being deprecated. Please use .Run.ID`

**What happened?**:

**What did you expect to happen?**:

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment**:

**Comment by ehotinger** [comment]
@northtyphoon do you think we should move this to the CLI? We could do it in the builder but I think the log message will be too deep and people won't read it. So maybe it's better at the very top when the CLI can validate `-t`

**Comment by sajayantony** [comment]
Yes might be a good idea to warn at the creation time. Are there any docs that refer build.id @mmacy ?

**Comment by sajayantony** [comment]
We won’t  stop existing APIs for a few weeks. 

Yes, all existing tasks needs to be re-created.

**Comment by ehotinger** [comment]
Closing since this is moved to the CLI. See the above PR for more information.
