### ISSUE TITLE
need Run.RegistryName

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr-builder#322]
**FEATURE REQUEST**:
When running `az acr helm repo add -n ` we need the RegistryName, not just the fully qualified registry url. We could provide examples for how to parse the fully qualified name, but it's too complex and risky for sub domains.

Alternatively, -n could accept the fully qualified registry name.

**Comment by ehotinger** [comment]
NB: must also consider the formats' of other registries, i.e. Quay, GCR, ECR, etc.

**Comment by ehotinger** [comment]
@djyou for `az acr helm` do you want `-n` to support the fully qualified registry name as well?

**Comment by djyou** [comment]
There is a different discussion of supporting dns (e.g., for `acr login`), but I have been a bit against of using `-n` for a dns name because across the CLI, `-n` means a resource name, for all commands, I haven't seen an exception.

The implementation is however very straightforward.
