### ISSUE TITLE
Support git-lfs

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#331]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened?**:
docker run acb build https://github.com/chzbrgr71/flask-tf.git -t flask-tf

The output image should include the files (https://github.com/chzbrgr71/flask-tf/blob/master/retrained_graph.pb) stored in git-lfs but it only includes the link file.

**Comment by sajayantony** [comment]
https://github.com/docker/hub-feedback/issues/500
