### ISSUE TITLE
Improve step log to tell user the container is launched

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#334]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened?**:

3893fe03a430: Pull complete
Downloaded newer image for abc.azurecr.io/container_static:latest
... after 50 minutes
Run ID: cf1 failed after 1h0m0s Error: failed during run, err: context deadline exceeded

**Comment by northtyphoon** [comment]
It turns out the issue is the entrypoint of the image was launching a website so the container never existed. As the container startup didn't output anything until the task or step timeout, it looked liked the container was stuck. Even worse, in azure-cli, the client might first timeout as it didn't get any update in 30 minutes which can further confuse the users.

Suggestion: add logs to tell the users the container is started...

**Comment by ehotinger** [comment]
If the line `Executing step ID...` exists and there are no errors afterwards, you should be able to safely assume that the container is running. A command like `docker run --rm busybox` produces no output. What's your suggestion to improve this?
