### ISSUE TITLE
ACR Build permission difference with ADD --chown

### ISSUE THREAD

**Issue by neumanndaniel** [Azure/acr-builder#344]
ACR Build does not honor or recognize the --chown flag, when using ADD to copy files into the container.

-> https://docs.docker.com/engine/reference/builder/#add

Example Dockerfile below. When building the container image via ACR Build, the image won't run throwing an error permission denied. But when building the container image locally with Docker CE everything works fine during runtime.

```
FROM ubuntu:bionic

LABEL maintainer="Daniel Neumann <https://www.danielstechblog.io>"
RUN groupadd -r -g 127001 container && \
    useradd -r -u 127001 -g container container

WORKDIR /webapp
ADD --chown=container:container /go-webapp .

USER container

EXPOSE 8080

ENTRYPOINT ./webapp
```

**Comment by ehotinger** [comment]
Closing this since I can't repro it after 18.06. Please re-open if you can find a current repro.

**Comment by jbohua** [comment]
> Ok. I found the issue, after digging a bit deeper into it. When building with ACR Build ADD --chown is recognized, but the permissions are different from when doing the build via Docker CE.
> 
> Permissions of the files when doing the build via ACR Build:
> 
> ```
> container@690c0fc91e29:/webapp$ ls -ahl
> total 6.3M
> drwxr-xr-x 1 root      root      4.0K Aug 16 07:13 .
> drwxr-xr-x 1 root      root      4.0K Aug 16 07:14 ..
> -rw-rw-rw- 1 container container 1.4K Jun  5 10:17 index.html
> -rw-rw-rw- 1 container container 6.3M Aug 15 17:49 webapp
> ```
> 
> Permissions of the files when doing the build via local Docker CE:
> 
> ```
> container@4c9669816ba0:/webapp$ ls -ahl
> total 6.3M
> drwxr-xr-x 1 root      root      4.0K Aug 15 18:45 .
> drwxr-xr-x 1 root      root      4.0K Aug 16 07:15 ..
> -rwxr-xr-x 1 container container 1.4K Jun  5 10:17 index.html
> -rwxr-xr-x 1 container container 6.3M Aug 15 17:49 webapp
> ```
> 
> In the end I can solve it with an additional line adding:
> RUN chmod +x ./webapp

I can still replicate this issue using the latest Microsoft-hosted agent ubuntu-20.04. 
And this workaround works well!!
