### ISSUE TITLE
Windows build: build step should use default isolation to avoid performance hit

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#346]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened?**:
For windows, all steps are run by hyperv isolation by default (https://github.com/Azure/acr-builder/blob/474e36f751f87dd1cd44c67f21527c47747c34f9/builder/context.go#L44) However it comes with a cost. The following is the comparison.

docker run docker build -h => 6-8 seconds
docker run --isolation=hyperv docker build -h  => 40-60 seconds

To avoid the performance hit, the docker-cli image (`docker`) in windows should be always compatible with the host os and the build step itself is run by default isolation.

**Comment by ehotinger** [comment]
We should probably improve the default for `build` specifically. Generally I think the default makes sense since people can't predict what the host OS is and would end up having to specify the isolation on every step otherwise.

**Comment by northtyphoon** [comment]
Agree. Build step needs to be handled specifically.
