### ISSUE TITLE
Detect file format and align with docker build

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#4]
Simplify local build to enable commands similar to docker build 
```
build -f Dockerfile/Compose.yml -t myregistry.azurecr.io\app:v1
```
We can assume that the docker sock is passed in for these scenarios. 
Also we can default the file to pick up Dockerfile by default followed by docker-compose.yml second.

**Comment by ehotinger** [comment]
Closing this since it's rather outdated. Compose is gone and we're actively reworking all the params anyways.

**Comment by ehotinger** [comment]
See #21
