### ISSUE TITLE
disableWorkingDirectoryOverride: true possibly not honored

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#403]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Possible Bug
**What happened?**:
The following yaml fails. 

**What did you expect to happen?**:
`pwd` should ouput /usr/src/app

**How do you reproduce it (as minimally and precisely as possible)?**:
```yaml
steps :
   -  cmd: | 
       bash -c 'echo "FROM alpine
       WORKDIR /usr/src/app
       CMD ["pwd"] " > Dockerfile'
   - build: -t test . 
   - cmd: test
     disableWorkingDirectoryOverride : true
```
az acr run -n myregistry -f acb.yaml .

**Environment**:

**Anything else we need to know?**:

**Comment by ehotinger** [comment]
Talked offline, quoting issue. Relevant code is [here](https://github.com/Azure/acr-builder/blob/master/builder/context.go#L91-L93).

**Comment by sajayantony** [comment]
Thanks for pointing out the quoting issue.
