### ISSUE TITLE
Refactor secret management

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#420]
**Is this a BUG REPORT or FEATURE REQUEST?**:
OPTIMIZATION

**What happened?**:
Need to  refactor Secret into OpaqueSecret, VaultSecret and MSISecret. 
Secret could be an interface that has ResolveChan and TimeoutChan, while other parameters like (ID, AKV, ArmResourceID) could come from VaultSecret/MSISecret. 

**What did you expect to happen?**:

**How do you reproduce it (as minimally and precisely as possible)?**:

**Environment**:

**Anything else we need to know?**:

**Comment by sajayantony** [comment]
Should we close this or reprioritize? @northtyphoon

**Comment by ehotinger** [comment]
I think leave as-is, but not high prio
