### ISSUE TITLE
Ignore stderr for fetching git metadata

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#448]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened?**:

Output error to stdout instead of stderr for git issues

**What did you expect to happen?**:

**How do you reproduce it (as minimally and precisely as possible)?**:

**Environment**:

**Anything else we need to know?**:

**Comment by ehotinger** [comment]
Why? @shahzzzam + @northtyphoon
