### ISSUE TITLE
Upgrade Docker CLI version for Windows 

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#451]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened?**:
The version for Docker CLI is very old. Need to upgrade to 18.09 and above.

https://github.com/Azure/acr-builder/blob/edf9b3e4c97c4d38d63ac40d21fe41d7c75b4e81/Windows.Dockerfile#L88

https://github.com/Azure/acr-builder/blob/edf9b3e4c97c4d38d63ac40d21fe41d7c75b4e81/baseimages/docker-cli/Windows.Dockerfile#L92

**Comment by ehotinger** [comment]
Note that it needs to be tested thoroughly (preferably with new automated tests), since last time we broke archival compatibility.

**Comment by ehotinger** [comment]
Note: also bump the Golang versions for this and Windows to be 1.12+
