### ISSUE TITLE
Failed to get image tag

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#50]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened?**:
Unable to use acr-builder container to build docker image. It fails at the end when trying to get image tag. 
**What did you expect to happen?**:
Build succeeded.
**How do you reproduce it (as minimally and precisely as possible)?**:
1. Run ```docker build --rm -t acr-builder .``` to create the acr-builder container image
2. Run ```./scripts/run-build.sh``` (The script basically uses acr-builder container to build acr-builder source code.)
2. Error 
time="2018-01-31T07:14:25Z" level=info msg="Running command docker image ls --digests --format \"{{.Digest}}\" acr-builder"
docker: 'image' is not a docker command.
See 'docker --help'.
**Anything else we need to know?**:

**Environment**:
Ubuntu 16.4 + Docker 17.12.0-ce

@shhsu

**Comment by northtyphoon** [comment]
The problem seems the acr-build image installs an old docker version: docker-1.11.2-r1.pre-install.

**Comment by shhsu** [comment]
Talked offline. Because of the fact that we would get a digest after we push. This might not be an issue
