### ISSUE TITLE
task does not display the appropriate error msg

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#525]
**Describe the bug**
task fails without appropriate error msg

The issue is that if the input external yaml file used for Aliasing, has incorrect key format. (i.e. may have characters other than allowed alphanumeric), the task errors out silently. But there is no error msg to say so. 

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**

**Comment by northtyphoon** [comment]
@shahzzzam  can you please clean up the bug description a little bit?

**Comment by northtyphoon** [comment]
Can you also clarify what is "input exteranal yaml"? I know it's related to aliasing only when I look at the PR. But the issue itself doesn't provide useful information.

**Comment by shahzzzam** [comment]
@northtyphoon updated
