### ISSUE TITLE
Tasks can't handle quotes for Dockerfile in Build step

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#537]
**Describe the bug**

If you have a step like:

```
steps: 
  - build: -f 'Dockerfile' -t 'xxxxx' .
```

It won't work as it will try to find a file named `'Dockerfile'` instead of `Dockerfile`. 

**To Reproduce**
You can run this task using the following YAML:

```
steps: 
  - build: -f 'Dockerfile' -t 'xxxxx' .
```
2019/10/26 01:24:40 Scanning for dependencies... 2019/10/26 01:24:41 Output from dependency scanning: error opening dockerfile: 'Dockerfile', error: open 'Dockerfile': no such file or directory

**Expected behavior**

It should be able to trim quotes and find the file.

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**

**Comment by xkszltl** [comment]
Also I'm wondering what happen if I use `'white space'`
