### ISSUE TITLE
Failed to download submodule in private git repo

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#538]
**Describe the bug**

If the git repo has submodule which is in private git repo, `acb download` fails error 'error initializing submodules:...'

Looks like the reason is https://github.com/Azure/acr-builder/blob/master/scan/git.go#L99 is unable to use the credential from master repo. One solution is to enable https://git-scm.com/docs/git-credential-cache.

**Comment by xkszltl** [comment]
Sounds like the right solution and should be enough to resolve our issue!

However, in a more complex scenario, if the submodule uses a different cred, this will also fail.
So should we also add options to

- Clone without submodule
- Provide a list of cred

**Comment by northtyphoon** [comment]
@xkszltl, thanks for the suggestion. We don't plan to support modules using different cred now. The PAT (Git or VSTS) token we supports is able to work for multiple repositories and projects.

**Comment by xkszltl** [comment]
I see.
FYI although we are not facing the multi-cred issue currently, we do have cross-vsts-org projects.

**Comment by northtyphoon** [comment]
You can choose what org your want to use the PAT https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops
