### ISSUE TITLE
ACR Tasks: Add retries around image download

### ISSUE THREAD

**Issue by shirl3y** [Azure/acr-builder#587]
**What is the problem you're trying to solve**
In our ACR task, there are occasional timeouts when downloading the image. We have retries for the entire task, but it doesn't help when the task is stuck during image download. 

**Describe the solution you'd like**
Add configuration for retries around image download explictly

**Additional context**

I've included the section where we run the image within our ACR task.
```
  - id: runimage
    cmd:  {{.Values.ScannerRegistry}}/{{.Values.ScannerRepo}}:{{.Values.ScannerTag}}
    timeout: 3600
    ignoreErrors: true
    retries: 3
    retryDelay: 5
```

**Comment by northtyphoon** [comment]
@chloeyin can you please take a look? cc: @shizhMSFT

**Comment by chloeyin** [comment]
> @chloeyin can you please take a look? cc: @shizhMSFT

Ok, I will take a look at it today.
