### ISSUE TITLE
Unable to get the version if the the version string is quoted

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#603]
The following task using `acr` alias command failed as the version was not parsed as `v1.1.0`. It was parsed as `"v1.1.0"` or `'v1.1.0'`

```yaml
version: "v1.1.0"
steps:
 - cmd: acr purge
```
or 
```yaml
versioin: 'v1.1.0'
 - cmd: acr purge
```

Related code https://github.com/Azure/acr-builder/blob/3128c04ad01ef5a9fcc1590b8894a8715759be59/graph/preprocessor.go#L318

Related issue: https://github.com/Azure/acr/issues/622

**Comment by chloeyin** [comment]
Are we going to trim all quotes when parsing the version field?

**Comment by northtyphoon** [comment]
> Are we going to trim all quotes when parsing the version field?

sounds good to me

**Comment by chloeyin** [comment]
> > Are we going to trim all quotes when parsing the version field?
> 
> sounds good to me. ideally we also want to check if the quotes match. cc: @estebanreyl

What happens if quotes don't match, eg:
`versioin: 'v1.1.0`
Should we return the string with quotes or still trim them, because it seems to be a strange string if we keep the quotes.

**Comment by northtyphoon** [comment]
> What happens if quotes don't match, eg: `versioin: 'v1.1.0`

If we follow yaml syntax, the version value is indeed `'v1.1.0`. However for our scenario, I agree we can do some optimization to tolerate such kind of user errors.

Did you try `version: ""v1.1.0"`? This is a invalid yaml string. Even it can pass version check here, I'm not sure if it will cause the confusion when the code tries to unmarshal the entire yaml file. 
 
In normal case I would suggest use yaml.Unmarshal to load the version value, if it's invalid yaml, throw error. 

I don't have strong opinion on this, either way seems reasonable.

**Comment by chloeyin** [comment]
> 
I prefer to trim all quotes, PTAL #607. 
cc @shizhMSFT
