### ISSUE TITLE
Provide useful error message when invoking builder without Image name for docker build

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#61]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report
**What happened?**:
Acr Builder error is not helpful when docker image not passed in with docker-file 
`ERRO[0032] invalid reference format`

**What did you expect to happen?**:
Should specify the the image was not passed in. 

**How do you reproduce it (as minimally and precisely as possible)?**:
Run builder with docker file and no image. 

**Anything else we need to know?**:

**Environment**:

**Comment by ehotinger** [comment]
Fixed in #62
