### ISSUE TITLE
Don't use os.Exit(-1)

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#64]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report.

**What happened?**:

If the builder fails to run, it will have its exit code be `255` (exit status out of range) if you run `docker inspect` on it. Values should be 0..255 inclusive, where 1 is a general failure. http://tldp.org/LDP/abs/html/exitcodes.html

**What did you expect to happen?**:

The container should produce standard exit codes from `docker inspect` based on different types of failures.

**How do you reproduce it (as minimally and precisely as possible)?**:

Crash the builder by passing in garbage arguments. Run `docker ps -a` and do `docker inspect`

**Fix**
This is fixed by simply changing `os.Exit(-1)` in `main.go` to be 1, but we should define standard exit codes so we can determine which piece failed.

**Comment by sajayantony** [comment]
Do you have a PR for this?

**Comment by ehotinger** [comment]
No, not yet. If `docker build`
