### ISSUE TITLE
Utilize docker build context to support tarball, git://, git@, github.com/, https, http

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#66]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened?**:
Currently, the acr-build download tarball or git source to local first and then pass the local context to docker build. Two issues.
1. The source is copied twice (remote->local->docker daemon).
2. It doesn't support some git path like pull request, eg, myrepo.git#pull/42/head.

**What did you expect to happen?**:
Pass the remote url to tarball or git source directly to docker build as [build context]
(https://docs.docker.com/engine/reference/commandline/build/#extended-description)

**Comment by ehotinger** [comment]
Closed from #98
