### ISSUE TITLE
Allow specifiying the target build stage to build

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#70]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

When building a multi-stage docker file, allow users to set the target build stage through --target option.

Reference: https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage-target

**Comment by ehotinger** [comment]
@northtyphoon I'm marking this as low priority for now. Multi-stage Dockerfiles aren't fully supported in a lot of the OCI work so we can have a big push for it all together later on I think.
