### ISSUE TITLE
Drop docker-compose support

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#80]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

We have discussed it a few times. Since we will evaluate our build configuration story and may look for other options, I suggest we drop docker-compose support and focus on dockerfile at the current stage. It will also help further cleanup and refactor the code base and reduce the image size.

@sajayantony  
@ehotinger

**Comment by ehotinger** [comment]
big 👍 from me - it will make it even harder to get rid of later if people somehow take a dependency on it

**Comment by sajayantony** [comment]
Approved.

**Comment by northtyphoon** [comment]
#81
