### ISSUE TITLE
Failed to build if the from command use arg

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#83]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened?**:
run acr-build using the following dockerfile with --docker-build-arg tag=latest

```
ARG tag
FROM ubuntu:${tag}
```

Build failed:
level=error msg="invalid reference format"

The dependency scan needs to expand arguments in from command.

**Comment by shhsu** [comment]
https://github.com/Azure/acr-builder/pull/86
